import React from "react";

export default React.createContext({
  token: null,
  userId: null,
  userName: null,
  notes: null,
  filteredNotes: null,
  trash: null,
  activeNote: null,
  activeNotebook: null,
  activeUI: "NOTES",
  tags: null,
  login: (token, userId, tokenExpiration) => {},
  logout: () => {},
  fetchUserData: () => {},
  setActiveNote: () => {},
  setActiveNotebook: () => {},
  pushNoteToServer: () => {},
  pushNoteToState: () => {},
  updateNoteBody: () => {},
  createNotebook: () => {},
  setActiveUI: () => {},
  updateNotes: () => {},
  softDeleteNote: () => {},
  noteToggleFavorite: () => {},
  moveNote: () => {},
  createTag: () => {},
  setFilteredNotes: () => {}
});
